---
- name: Add new client to WireGuard server
  hosts: raspberry_pi
  become: yes
  tasks:
    - name: Generate client keys
      command: wg genkey | tee /etc/wireguard/client_privatekey | wg pubkey > /etc/wireguard/client_publickey
      args:
        creates: /etc/wireguard/client_privatekey
    - name: Configure WireGuard client
      template:
        src: templates/client.conf.j2
        dest: /etc/wireguard/clients/{{ client_name }}.conf
    - name: Add client to WireGuard server configuration
      command: wg set wg0 peer {{ lookup('file', '/etc/wireguard/client_publickey') }} allowed-ips {{ hostvars['client']['ansible_host'] }}/32
    - name: Restart WireGuard
      systemd:
        name: wg-quick@wg0
        state: restarted
    - name: Fetch client configuration file to local machine
      fetch:
        src: /etc/wireguard/clients/{{ client_name }}.conf
        dest: ./{{ client_name }}.conf
        flat: yes

- name: Install WireGuard on client
  hosts: client
  tasks:
    - name: Install WireGuard
      script: scripts/client_install_wireguard.sh
    - name: Transfer client configuration to client machine
      copy:
        src: ./{{ client_name }}.conf
        dest: /home/{{ ansible_user }}/{{ client_name }}.conf
        mode: '0600'
