---
- hosts: localhost
  gather_facts: yes  # Enable gathering facts about the server
  become: yes
  tasks:
    - name: Create client keys file if not exists
      file:
        path: /etc/wireguard/client_keys
        state: touch

    - name: Set permissions for client keys file
      file:
        path: /etc/wireguard/client_keys
        mode: '0644'

    - name: Generate client private key
      command: wg genkey
      register: client_private_key
      changed_when: false
      check_mode: no

    - name: Generate client public key
      command: "echo {{ client_private_key.stdout }} | wg pubkey"
      register: client_public_key
      changed_when: false
      check_mode: no

    - name: Get server IP address
      set_fact:
        server_ip: "{{ ansible_default_ipv4.address }}"  # Extract the server's default IPv4 address

    - name: Render client configuration template
      template:
        src: /templates/client_template.conf.j2  # Corrected path to the template file
        dest: "/etc/wireguard/clients/client_{{ item }}.conf"
      vars:
        client_private_key: "{{ client_private_key.stdout }}"
        client_index: "{{ item }}"
        server_public_key: "{{ server_public_key.stdout }}"
        wg_port: "{{ wg_port }}"
        wg_allowed_ips: "{{ wg_allowed_ips }}"
        server_ip: "{{ server_ip }}"
      loop: "{{ range(2, 255) }}"
      loop_control:
        loop_var: item

    - name: Restart WireGuard
      systemd:
        name: wg-quick@{{ wg_interface }}
        state: restarted
