---
- hosts: macos_clients
  become: yes
  tasks:
    - name: Install Homebrew (if not installed)
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install WireGuard using Homebrew
      homebrew:
        name: wireguard-tools
        state: present

    - name: Create WireGuard configuration directory
      file:
        path: /usr/local/etc/wireguard
        state: directory
        mode: '0700'

    - name: Copy WireGuard configuration
      copy:
        src: /etc/wireguard/clients/client_{{ client_ip }}.conf
        dest: /usr/local/etc/wireguard/wg0.conf
        mode: '0600'

    - name: Enable and start WireGuard
      shell: |
        wg-quick up /usr/local/etc/wireguard/wg0.conf
