---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create WireGuard directory
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate server private key
  command: wg genkey
  register: server_private_key
  changed_when: false
  check_mode: no

- name: Generate server public key
  command: "echo {{ server_private_key.stdout }} | wg pubkey"
  register: server_public_key
  changed_when: false
  check_mode: no

- name: Configure WireGuard
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/{{ wg_interface }}.conf
    mode: '0600'

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@{{ wg_interface }}
    enabled: yes
    state: started
